services:
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:26.1.0
    command: ["start-dev"]
    ports:
      - 9090:8080
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
