spring:
  application:
    name: cofidential-client
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9090/realms/oauthrealm/protocol/openid-connect/certs
server:
  port: 8080
